APP_KEY="29b1de684be26d084376d02695c1a2fa"
RUN_MODE="DEV"
DEBUG_MODE=true
BASE_URL="https://api.warpin-message.com/"
REDIS_HOST="redis"
REDIS_PORT=6379
REDIS_USERNAME=""
REDIS_PASSWORD=""
RABBITMQ_HOST="rabbitmq"
RABBITMQ_PORT="5672"
RABBITMQ_USERNAME="guest"
RABBITMQ_PASSWORD="guest"